### ISSUE TITLE
Possibility to scroll vertically and horizontal at the same time?

### ISSUE THREAD

**Issue by xzilja** [xd-tayde/pixi-better-scroller#7]
Firs of all, thank you for this lib, it's been a pleasure to work with so far.
I wanted to ask if it is possible to allow horizontal and vertical scrolling at the same time? For example scrolling through a game map?

**Comment by xd-tayde** [comment]
it's not support in now version. but it's a good idea, i will try. thanks!

**Comment by xd-tayde** [comment]
try the new version 0.2.0🤗
